export default {
  INVALID_DATA: 'INVALID_DATA',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  INVALID_DISTANCE: 'INVALID_DISTANCE',
  INVALID_DRIVER: 'INVALID_DRIVER',
  NO_RIDES_FOUND: 'NO_RIDES_FOUND',
};
