services:
  frontend:
    build:
      context: ./app-shopper-challenge
      dockerfile: Dockerfile
    command: bash -c "npm start"
    container_name: app_shopper_challenge_frontend
    ports:
      - "80:80"
    restart: always
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "npm run prisma:migration && npm run prisma:seed && npm start"
    container_name: app_shopper_challenge_backend
    depends_on:
      app_mysql:
        condition:
          service_healthy
    env_file:
      - ./backend/.env
      - .env
    ports:
      - "8080:8080"
    restart: always

  app_mysql:
    image: mysql:8.0
    container_name: mysql_shopper_challenge_backend
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: abc12345678
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 15
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - app_volume:/var/lib/mysql

volumes:
  app_volume:
    driver: local
